default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight Internal"
  lane :beta do
    sh("pod install")

    setup_ci(force: true)

    match(
      type: "appstore",
      readonly: true
    )

    build_app(
      workspace: "WONNIT.xcworkspace",
      scheme: "WONNIT",
      export_method: "app-store",
      include_bitcode: true,
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.dohyeoplim.WONNIT" => "match AppStore com.dohyeoplim.WONNIT"
        }
      }
    )

    upload_to_testflight
  end
end

