default_platform(:ios)

def get_api_key
  app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY"],
    is_key_content_base64: true
  )
end

platform :ios do
  desc "Deploy to TestFlight Internal"
  lane :beta do
    sh("pod install")

    match(type: "appstore", api_key: get_api_key, readonly: true)

    unlock_keychain(
      path: lane_context[SharedValues::MATCH_KEYCHAIN_PATH],
      password: lane_context[SharedValues::MATCH_KEYCHAIN_PASSWORD]
    )

    build_app(
      workspace: "WONNIT.xcworkspace",
      scheme: "WONNIT",
      export_method: "app-store",
      include_bitcode: true,
    )

    upload_to_testflight(
      api_key: get_api_key,
      distribute_external: false,
    )
  end
end

