default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight Internal"
  lane :beta do
    sh("pod install")
    match(type: "appstore")

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: false
    )

    build_app(
      workspace: "WONNIT.xcworkspace",
      scheme: "WONNIT",
      export_method: "app-store",
      include_bitcode: true
    )

    upload_to_testflight(
      api_key: api_key,
      distribute_external: false, # internal only
      skip_waiting_for_build_processing: true
    )
  end
end

